version: '2.1'

services:
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - "15672:15672"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888