version: '2.1'

services:
  rabbitmq:
    image: rabbitmq:3.7.8-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
  rabbitmq-publisher:
    image: internet-of-plants:latest
    depends_on:
      - rabbitmq
    environment:
      ROLE: publisher
    links:
      - rabbitmq
  rabbitmq-subscriber:
    image: internet-of-plants:latest
    depends_on:
      - rabbitmq
      - rabbitmq-publisher
    environment:
      ROLE: subscriber
    links:
      - rabbitmq
